# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: booking.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'booking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\x12\x07\x62ooking\"\x13\n\x05Movie\x12\n\n\x02id\x18\x01 \x01(\t\";\n\x0b\x42ookingDate\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x1e\n\x06movies\x18\x02 \x03(\x0b\x32\x0e.booking.Movie\">\n\x07\x42ooking\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12#\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\x14.booking.BookingDate\"\x14\n\x12GetBookingsRequest\"9\n\x13GetBookingsResponse\x12\"\n\x08\x62ookings\x18\x01 \x03(\x0b\x32\x10.booking.Booking\")\n\x17GetBookingByUserRequest\x12\x0e\n\x06userid\x18\x01 \x01(\t\"=\n\x18GetBookingByUserResponse\x12!\n\x07\x62ooking\x18\x01 \x01(\x0b\x32\x10.booking.Booking\"G\n\x11\x41\x64\x64\x42ookingRequest\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\"\n\x04\x64\x61te\x18\x02 \x01(\x0b\x32\x14.booking.BookingDate\"%\n\x12\x41\x64\x64\x42ookingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xfa\x01\n\x0e\x42ookingService\x12H\n\x0bGetBookings\x12\x1b.booking.GetBookingsRequest\x1a\x1c.booking.GetBookingsResponse\x12W\n\x10GetBookingByUser\x12 .booking.GetBookingByUserRequest\x1a!.booking.GetBookingByUserResponse\x12\x45\n\nAddBooking\x12\x1a.booking.AddBookingRequest\x1a\x1b.booking.AddBookingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOVIE']._serialized_start=26
  _globals['_MOVIE']._serialized_end=45
  _globals['_BOOKINGDATE']._serialized_start=47
  _globals['_BOOKINGDATE']._serialized_end=106
  _globals['_BOOKING']._serialized_start=108
  _globals['_BOOKING']._serialized_end=170
  _globals['_GETBOOKINGSREQUEST']._serialized_start=172
  _globals['_GETBOOKINGSREQUEST']._serialized_end=192
  _globals['_GETBOOKINGSRESPONSE']._serialized_start=194
  _globals['_GETBOOKINGSRESPONSE']._serialized_end=251
  _globals['_GETBOOKINGBYUSERREQUEST']._serialized_start=253
  _globals['_GETBOOKINGBYUSERREQUEST']._serialized_end=294
  _globals['_GETBOOKINGBYUSERRESPONSE']._serialized_start=296
  _globals['_GETBOOKINGBYUSERRESPONSE']._serialized_end=357
  _globals['_ADDBOOKINGREQUEST']._serialized_start=359
  _globals['_ADDBOOKINGREQUEST']._serialized_end=430
  _globals['_ADDBOOKINGRESPONSE']._serialized_start=432
  _globals['_ADDBOOKINGRESPONSE']._serialized_end=469
  _globals['_BOOKINGSERVICE']._serialized_start=472
  _globals['_BOOKINGSERVICE']._serialized_end=722
# @@protoc_insertion_point(module_scope)
