# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import booking_pb2 as booking__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in booking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookingServiceStub(object):
    """Service Booking
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBookings = channel.unary_unary(
                '/booking.BookingService/GetBookings',
                request_serializer=booking__pb2.GetBookingsRequest.SerializeToString,
                response_deserializer=booking__pb2.GetBookingsResponse.FromString,
                _registered_method=True)
        self.GetBookingByUser = channel.unary_unary(
                '/booking.BookingService/GetBookingByUser',
                request_serializer=booking__pb2.GetBookingByUserRequest.SerializeToString,
                response_deserializer=booking__pb2.GetBookingByUserResponse.FromString,
                _registered_method=True)
        self.AddBooking = channel.unary_unary(
                '/booking.BookingService/AddBooking',
                request_serializer=booking__pb2.AddBookingRequest.SerializeToString,
                response_deserializer=booking__pb2.AddBookingResponse.FromString,
                _registered_method=True)


class BookingServiceServicer(object):
    """Service Booking
    """

    def GetBookings(self, request, context):
        """Récupérer toutes les réservations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBookingByUser(self, request, context):
        """Récupérer les réservations d'un utilisateur spécifique
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBooking(self, request, context):
        """Ajouter une réservation pour un utilisateur
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBookings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookings,
                    request_deserializer=booking__pb2.GetBookingsRequest.FromString,
                    response_serializer=booking__pb2.GetBookingsResponse.SerializeToString,
            ),
            'GetBookingByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookingByUser,
                    request_deserializer=booking__pb2.GetBookingByUserRequest.FromString,
                    response_serializer=booking__pb2.GetBookingByUserResponse.SerializeToString,
            ),
            'AddBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBooking,
                    request_deserializer=booking__pb2.AddBookingRequest.FromString,
                    response_serializer=booking__pb2.AddBookingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'booking.BookingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('booking.BookingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookingService(object):
    """Service Booking
    """

    @staticmethod
    def GetBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/GetBookings',
            booking__pb2.GetBookingsRequest.SerializeToString,
            booking__pb2.GetBookingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBookingByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/GetBookingByUser',
            booking__pb2.GetBookingByUserRequest.SerializeToString,
            booking__pb2.GetBookingByUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/AddBooking',
            booking__pb2.AddBookingRequest.SerializeToString,
            booking__pb2.AddBookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
