# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: showtime.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'showtime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshowtime.proto\x12\x08showtime\"\x15\n\x13GetShowtimesRequest\"=\n\x14GetShowtimesResponse\x12%\n\tshowtimes\x18\x01 \x03(\x0b\x32\x12.showtime.Showtime\")\n\x19GetShowtimesByDateRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"B\n\x1aGetShowtimesByDateResponse\x12$\n\x08showtime\x18\x01 \x01(\x0b\x32\x12.showtime.Showtime\"(\n\x08Showtime\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t2\xc1\x01\n\x0fShowtimeService\x12M\n\x0cGetShowtimes\x12\x1d.showtime.GetShowtimesRequest\x1a\x1e.showtime.GetShowtimesResponse\x12_\n\x12GetShowtimesByDate\x12#.showtime.GetShowtimesByDateRequest\x1a$.showtime.GetShowtimesByDateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'showtime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSHOWTIMESREQUEST']._serialized_start=28
  _globals['_GETSHOWTIMESREQUEST']._serialized_end=49
  _globals['_GETSHOWTIMESRESPONSE']._serialized_start=51
  _globals['_GETSHOWTIMESRESPONSE']._serialized_end=112
  _globals['_GETSHOWTIMESBYDATEREQUEST']._serialized_start=114
  _globals['_GETSHOWTIMESBYDATEREQUEST']._serialized_end=155
  _globals['_GETSHOWTIMESBYDATERESPONSE']._serialized_start=157
  _globals['_GETSHOWTIMESBYDATERESPONSE']._serialized_end=223
  _globals['_SHOWTIME']._serialized_start=225
  _globals['_SHOWTIME']._serialized_end=265
  _globals['_SHOWTIMESERVICE']._serialized_start=268
  _globals['_SHOWTIMESERVICE']._serialized_end=461
# @@protoc_insertion_point(module_scope)
